version: '3.2'
services:
  mysqldb:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql

  finance-app:
    image: finance-app:1.0
    ports:
      - 8080:8080

volumes:
  mysql-data:
    driver: local